# Define to instance for prod config

# Define the app name
spring.application.name=auth-api
# Define database server
spring.datasource.url=${DB_SERVER}
# Define server database user
spring.datasource.username=${DB_USER}
# Define server database password access
spring.datasource.password=${DB_PASSWORD}
# Define rules for table changes
spring.jpa.hibernate.ddl-auto=update
# Define rules for sql syntax
spring.jpa.show-sql=true
# Define a personalized app port
server.port=8081