# Define database server
spring.datasource.url=${DB_SERVER:jdbc:postgresql://192.168.100.113/dev}
# Define server database user
spring.datasource.username=${DB_USER:rvegag}
# Define server database password access
spring.datasource.password=${DB_PASSWORD:jiprId0icukicr1}
# Define rules for table changes
spring.jpa.hibernate.ddl-auto=update
# Define rules for sql syntax
spring.jpa.show-sql=true

