# Define the app name
spring.application.name=auth-api
# Define database server
spring.datasource.url=jdbc:postgresql://{server}:5432/{database}
# Define server database user
spring.datasource.username={user}
# Define server database password access
spring.datasource.password={password}
# Define rules for table changes
spring.jpa.hibernate.ddl-auto=update
# Define rules for sql syntax
spring.jpa.show-sql=true
# Define a personalized app port
server.port=8081
