# Define to instance for dev config

# Define the app name
spring.application.name=auth-api
# Define database server
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/identity_db
# Define server database user
spring.datasource.username=ricardo
# Define server database password access
spring.datasource.password=r1c4rd0
# Define rules for table changes
spring.jpa.hibernate.ddl-auto=update
# Define rules for sql syntax
spring.jpa.show-sql=true
# Define a personalized app port
server.port=8081
# Swagger Config
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true